import * as Contracts from "../../packages/contracts/src/index.js";

export const S17_STAFF_SCHEMA_NAMES = [
  "StaffWorkItemSchema",
  "StaffWorkListQuerySchema",
  "StaffWorkParamsSchema",
  "StaffWorkResponseSchema",
  "StaffWorkCollectionResponseSchema",
  "StaffAcceptAppointmentInputSchema",
  "StaffRejectAppointmentInputSchema",
  "StaffClaimHandoffInputSchema",
  "StaffResolveHandoffInputSchema",
  "StaffAcknowledgeInputSchema",
  "StaffAttendanceInputSchema",
  "StaffRevenueInputSchema",
  "StaffOutcomeSchema",
  "StaffOutcomeCollectionResponseSchema",
  "StaffMutationResultSchema",
  "StaffMutationResponseSchema",
] as const;

export const S19_STAFF_SCHEMA_NAMES = ["StaffMeSchema", "StaffMeResponseSchema"] as const;

export const S19_WIDGET_SCHEMA_NAMES = [
  "WidgetEmbedGrantCreateInputSchema",
  "WidgetEmbedGrantCreateResponseSchema",
  "WidgetEmbedGrantSchema",
  "WidgetEmbedPolicyInputSchema",
  "WidgetEmbedPolicyResponseSchema",
  "WidgetEmbedPolicySchema",
  "WidgetEmbedSessionRedeemInputSchema",
  "WidgetEmbedSessionRedeemResponseSchema",
] as const;

export const PUBLIC_STATIC_SCHEMA_NAMES = {
  ai: [
    "AgentDecisionLanguageSchema",
    "AgentIntentSchema",
    "AgentFactualClaimKindSchema",
    "AgentFactualClaimSourceTypeSchema",
    "AgentActionTypeSchema",
    "AgentInformationFieldSchema",
    "AgentHandoffReasonSchema",
    "AgentMessageModeSchema",
    "AgentRiskFlagSchema",
    "AgentAppointmentPreferenceSchema",
    "AgentExtractedFactsSchema",
    "AgentFactualClaimSchema",
    "AgentDecisionActionSchema",
    "AgentDecisionMessageSchema",
    "AgentDecisionSafetySchema",
    "AgentDecisionV1Schema",
  ],
  api: [
    ...S17_STAFF_SCHEMA_NAMES,
    ...S19_STAFF_SCHEMA_NAMES,
    "ApiErrorCodeSchema",
    "ValidationIssueSchema",
    "ProblemSchema",
    "OpaqueCursorSchema",
    "PageSizeSchema",
    "PaginationRequestSchema",
    "PaginationMetaSchema",
    "ResponseMetaSchema",
  ],
  channel: [
    "ChannelTypeSchema",
    "InboundMessageKindSchema",
    "ChannelMediaKindSchema",
    "ChannelTextFormatSchema",
    "ChannelFailureCategorySchema",
    "ExternalChannelEventIdSchema",
    "ExternalChannelAccountIdSchema",
    "ExternalChannelConversationIdSchema",
    "ExternalChannelMessageIdSchema",
    "ExternalChannelParticipantIdSchema",
    "ProviderMediaReferenceSchema",
    "ChannelActionTokenSchema",
    "ChannelIdempotencyKeySchema",
    "InboundTextContentSchema",
    "InboundQuickReplyContentSchema",
    "InboundAttachmentContentSchema",
    "InboundDeliveryStatusContentSchema",
    "InboundUnsupportedContentSchema",
    "InboundChannelContentSchema",
    "CanonicalInboundEventSchema",
    "OutboundQuickReplySchema",
    "OutboundChannelContentSchema",
    "SendChannelMessageSchema",
    "ChannelCapabilitiesSchema",
  ],
  configuration: [
    "BusinessHoursIntervalSchema",
    "BusinessPolicyListFilterSchema",
    "BusinessPolicySchema",
    "BusinessPolicyTypeSchema",
    "CancelLocationClosureInputSchema",
    "ChangeServiceLocationInputSchema",
    "ConfigurationCodeSchema",
    "ConfigurationIdempotencyKeySchema",
    "ConfigurationKeySchema",
    "ConfigurationRootStatusSchema",
    "ContentHashSchema",
    "CreateBusinessPolicyDraftInputSchema",
    "CreateFaqDraftInputSchema",
    "CreateLocationClosureInputSchema",
    "CreateLocationInputSchema",
    "CreateServiceInputSchema",
    "CreateServicePriceDraftInputSchema",
    "DeactivateLocationInputSchema",
    "DeactivateServiceInputSchema",
    "EffectiveIntervalSchema",
    "FaqListFilterSchema",
    "FaqSchema",
    "IanaTimeZoneSchema",
    "LocalDateSchema",
    "LocalizedTextSchema",
    "LocalTimeSchema",
    "LocationClosureKindSchema",
    "LocationClosureRecordSchema",
    "LocationClosureStatusSchema",
    "LocationListFilterSchema",
    "LocationPublicContactSchema",
    "LocationPublishedVersionSchema",
    "LocationRootSchema",
    "PublishBusinessPolicyInputSchema",
    "PublishedBusinessKnowledgeRequestSchema",
    "PublishedBusinessKnowledgeSchema",
    "PublishedBusinessKnowledgeV2Schema",
    "PublishedConfigurationProvenanceSchema",
    "PublishFaqInputSchema",
    "PublishLocationInputSchema",
    "PublishServiceInputSchema",
    "PublishServicePriceInputSchema",
    "QualificationDisqualificationReasonSchema",
    "QualificationEvidenceKeySchema",
    "QualificationOutcomeSchema",
    "QualificationPolicyV1RulesSchema",
    "RetireBusinessPolicyInputSchema",
    "RetireFaqInputSchema",
    "RetireServicePriceInputSchema",
    "ServiceListFilterSchema",
    "ServiceLocationRecordSchema",
    "ServiceLocationStatusSchema",
    "ServicePriceListFilterSchema",
    "ServicePriceRecordSchema",
    "ServicePriceTermsSchema",
    "ServicePriceTypeSchema",
    "ServicePublishedVersionSchema",
    "ServiceRootSchema",
    "SupersedeLocationClosureInputSchema",
    "UpdateBusinessPolicyDraftInputSchema",
    "UpdateFaqDraftInputSchema",
    "UpdateServicePriceDraftInputSchema",
    "VersionedConfigurationStatusSchema",
    "WeekdaySchema",
    "WeeklyBusinessHoursSchema",
  ],
  conversation: [
    "StaffContactIdentityTypeV2Schema",
    "StaffContactIdentityV2Schema",
    "StaffContactV2Schema",
    "StaffContactResponseV2Schema",
    "StaffConversationParticipantV2Schema",
    "StaffConversationV2Schema",
    "StaffConversationResponseV2Schema",
    "StaffConversationCollectionResponseV2Schema",
    "StaffContactIdentitySchema",
    "StaffContactIdentityStatusSchema",
    "StaffContactIdentityTypeSchema",
    "StaffContactIdentityValidationStatusSchema",
    "StaffContactReadParamsSchema",
    "StaffContactResponseSchema",
    "StaffContactSchema",
    "StaffContactStatusSchema",
    "StaffConversationAutomationModeSchema",
    "StaffConversationCollectionResponseSchema",
    "StaffConversationListQuerySchema",
    "StaffConversationParticipantSchema",
    "StaffConversationReadParamsSchema",
    "StaffConversationResponseSchema",
    "StaffConversationSchema",
    "StaffConversationStatusSchema",
    "StaffLeadCollectionResponseSchema",
    "StaffLeadListQuerySchema",
    "StaffLeadReadParamsSchema",
    "StaffLeadResponseSchema",
    "StaffLeadSchema",
    "StaffLeadStatusSchema",
    "StaffMessageCollectionResponseSchema",
    "StaffMessageDeliveryStatusSchema",
    "StaffMessageDirectionSchema",
    "StaffMessageListQuerySchema",
    "StaffMessageProcessingStatusSchema",
    "StaffMessageSchema",
    "StaffMessageSenderTypeSchema",
  ],
  event: [
    "AppointmentRequestConfirmedDomainEventV2Schema",
    "AppointmentRequestConfirmedDomainEventPayloadV2Schema",
    "ContactIdentityAddedDomainEventV2Schema",
    "ContactIdentityAddedDomainEventPayloadV2Schema",
    "DomainEventNameSchema",
    "DomainAggregateTypeSchema",
    "DomainEventSchema",
    "LeadReopenedDomainEventV2Schema",
    "LeadReopenedDomainEventPayloadV2Schema",
  ],
  shared: [
    "ActorRefSchema",
    "UuidV7Schema",
    "ResourceIdSchema",
    "OrganizationIdSchema",
    "UserIdSchema",
    "MembershipIdSchema",
    "LocationIdSchema",
    "ServiceIdSchema",
    "ContactIdSchema",
    "LeadIdSchema",
    "ConversationIdSchema",
    "MessageIdSchema",
    "AppointmentRequestIdSchema",
    "HandoffIdSchema",
    "ChannelConnectionIdSchema",
    "AiRunIdSchema",
    "EventIdSchema",
    "RequestIdSchema",
    "CorrelationIdSchema",
    "CausationIdSchema",
    "SchemaIdSchema",
    "LocaleSchema",
    "CurrencyCodeSchema",
    "MoneySchema",
    "UtcTimestampSchema",
    "SchemaVersionSchema",
    "ResourceVersionSchema",
    "AggregateVersionSchema",
  ],
  widget: [
    "WidgetAcceptedMessageSchema",
    "WidgetConversationCreateInputSchema",
    "WidgetConversationCreateResponseSchema",
    "WidgetConversationCreateResultSchema",
    "WidgetConversationReadParamsSchema",
    "WidgetConversationResponseSchema",
    "WidgetConversationSchema",
    ...S19_WIDGET_SCHEMA_NAMES,
    "WidgetMessageCollectionResponseSchema",
    "WidgetMessageCreateInputSchema",
    "WidgetMessageCreateResponseSchema",
    "WidgetMessageCreateResultSchema",
    "WidgetMessageListQuerySchema",
    "WidgetMessageSchema",
    "WidgetPublicConfigurationSchema",
    "WidgetSessionCreateInputSchema",
    "WidgetSessionCreateResponseSchema",
    "WidgetSessionSchema",
    "WidgetTextMessageInputSchema",
  ],
} as const;

export type ContractCategory = keyof typeof PUBLIC_STATIC_SCHEMA_NAMES;

export type PublicContractEntry = {
  readonly category: ContractCategory;
  readonly exportName: string;
  readonly schema: unknown;
};

const publicExports = new Map<string, unknown>(Object.entries(Contracts));
const CONTRACT_CATEGORIES = [
  "ai",
  "api",
  "channel",
  "configuration",
  "conversation",
  "event",
  "shared",
  "widget",
] as const;

const requirePublicExport = (exportName: string) => {
  const value = publicExports.get(exportName);

  if (value === undefined) {
    throw new TypeError(`Missing public contract export: ${exportName}`);
  }

  return value;
};

export const getPublicContractCatalog = (): readonly PublicContractEntry[] => {
  const staticEntries = CONTRACT_CATEGORIES.flatMap((category) =>
    PUBLIC_STATIC_SCHEMA_NAMES[category].map((exportName) => ({
      category,
      exportName,
      schema: requirePublicExport(exportName),
    })),
  );

  const eventEntries = Contracts.DOMAIN_EVENT_NAMES.flatMap((eventName) => [
    {
      category: "event" as const,
      exportName: `DomainEventSchemas[${JSON.stringify(eventName)}]`,
      schema: Contracts.DomainEventSchemas[eventName],
    },
    {
      category: "event" as const,
      exportName: `DomainEventPayloadSchemas[${JSON.stringify(eventName)}]`,
      schema: Contracts.DomainEventPayloadSchemas[eventName],
    },
  ]);

  return [...staticEntries, ...eventEntries].sort((left, right) =>
    left.exportName.localeCompare(right.exportName),
  );
};
